"""fixed the relationship table

Revision ID: 0970a2d32448
Revises: 2249a5159174
Create Date: 2023-09-10 10:14:16.793855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0970a2d32448'
down_revision = '2249a5159174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('lastMessageAt', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('serverId', postgresql.UUID(), nullable=False))
    op.add_column('conversations', sa.Column('creatorId', postgresql.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('name', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('isGroup', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('memberOneId', postgresql.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('memberTwoId', postgresql.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('messageIds', postgresql.ARRAY(postgresql.UUID()), nullable=True))
    op.add_column('conversations', sa.Column('directMessageIds', postgresql.ARRAY(postgresql.UUID()), nullable=True))
    op.create_foreign_key(None, 'conversations', 'members', ['memberTwoId'], ['id'])
    op.create_foreign_key(None, 'conversations', 'servers', ['serverId'], ['id'])
    op.create_foreign_key(None, 'conversations', 'members', ['memberOneId'], ['id'])
    op.create_foreign_key(None, 'conversations', 'members', ['creatorId'], ['id'])
    op.drop_column('conversations', 'memberIds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('memberIds', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'directMessageIds')
    op.drop_column('conversations', 'messageIds')
    op.drop_column('conversations', 'memberTwoId')
    op.drop_column('conversations', 'memberOneId')
    op.drop_column('conversations', 'isGroup')
    op.drop_column('conversations', 'name')
    op.drop_column('conversations', 'creatorId')
    op.drop_column('conversations', 'serverId')
    op.drop_column('conversations', 'lastMessageAt')
    op.drop_column('conversations', 'createdAt')
    # ### end Alembic commands ###
