"""enum type enabled

Revision ID: 72396746d801
Revises: 81f83781fe93
Create Date: 2023-09-09 19:19:27.872608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72396746d801'
down_revision = '81f83781fe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum type creation
    role_enum = postgresql.ENUM('ADMIN', 'MODERATOR', 'GUEST', name='memberrole')
    role_enum.create(op.get_bind())
    op.add_column('members', sa.Column('role', role_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'role')
    role_enum = sa.Enum('ADMIN', 'MODERATOR', 'GUEST', name='memberrole')
    role_enum.drop(op.get_bind())

    # ### end Alembic commands ###
